#!/bin/bash

esptool.py --port /dev/tty.wchusbserialfd130  erase_flash
esptool.py --port /dev/tty.wchusbserialfd130 --baud 115200 write_flash -fm dio -ff 40m 0x0000 ../MicroPython/esp8266-20180511-v1.9.4.bin
for file in *.py
do 
   echo $file
   ampy --port /dev/tty.wchusbserialfd130 put $file
done

